### ISSUE TITLE
Logout functionality

### ISSUE THREAD

**Issue by lorenzcarva** [KeyScribe/keyscribe-webapp#26]
As a user, I want to be able to log out from a button in the NavBar.

**Comment by AndrewL-64** [comment]
Hey Lorenz, I merged my work with yours. If you want to test using Docker, run `docker compose up -d` in the main directory. Let me know if there's any issues so I can fix asap.

**Comment by lorenzcarva** [comment]
Thank you Andrew! I'll take a look at it.

**Comment by AndrewL-64** [comment]
There might be .env issues with the backend. Make sure backend .env has a couple of extra variables:
```
NODE_ENV=dev
PORT=8000
DEV_BACKEND=https://localhost:8000
...
DB_HOST: '52.168.92.118'
FRONTEND_CORS=http://localhost:3000
```
