### ISSUE TITLE
Keystroke data storage

### ISSUE THREAD

**Issue by lorenzcarva** [KeyScribe/keyscribe-webapp#7]
As a user, I want to record a piece of music starting from when I press a "Start Recording" Button, either on the webapp or physical board. This will start storing button-press information into a consistent data structure. Not concerned with sheet-music conversion for now.

- [x] Frontend: Clickable start button that enables this recording
- [x] Frontend: Clickable stop button for terminating recording
- [x] Frontend: Convert key data into MIDI file
- [x] Backend: Send key data to frontend
- [x] Database: Table for storing information
- [x] Raspberry Pi: Transmit button info & timestamps

**Comment by lorenzcarva** [comment]
Resources:

- [Music Data Structures](https://www.music-software-development.com/music-data-structures.html)
- [MIDI Tutorial](https://www.music-software-development.com/midi-tutorial.html)
- [MUI Installation](https://mui.com/material-ui/getting-started/installation/)
- [Free Midi Editor](https://midieditor.org/index.php?category=manual&subcategory=midi-overview)
- [Free Midi Binary File Viewer](https://jeffbourdier.github.io/midiopsy/)
- [midi-writer-js](https://www.npmjs.com/package/midi-writer-js)

**Comment by lorenzcarva** [comment]
React piano installations:
- npm install --global yarn
- yarn add react-piano

**Comment by elsaosmani** [comment]
- [MIDI Programming Video](https://www.youtube.com/watch?v=040BKtnDdg0)
- [Code](https://github.com/OneLoneCoder/Javidx9/blob/master/PixelGameEngine/SmallerProjects/OneLoneCoder_PGE_MIDI.cpp)

**Comment by lorenzcarva** [comment]
This feature only works if something was actually recorded, when I test it without the Pi's the data is not updated, so it will either not download anything or re-download the last thing that was downloaded.
